### ISSUE TITLE
io.adapter not work for me

### ISSUE THREAD

**Issue by pineli** [stoshiya/socket.io-redis-sample#1]
Hey there, I saw your sample and is exactly which I need but here it not work. Simply does nothing... my Redis is with default configs (localhost, 6379). I already tried use the modules of the your package.json and also the newer versions but not work. Can you help me it? Thanks

**Comment by pineli** [comment]
published messages are "consumed immediately" so nothing gets stored. Got it!

**Comment by dka09** [comment]
I have similar problem. If I launch 2 server (localhost:3000 and localhost:3001) and I post a message on server on port 3000, it is not shown on webpage on server on port 3001. Is this the problem you had?
